import { Problem3Divider } from './Problem3Divider';
import { ZeroShearQuizL3 } from './ZeroShearQuizL3';
import {
  Problem3Step0,
  Problem3Step1,
  Problem3Step2,
  Problem3Step3,
  Problem3Step4,
  Problem3Step5,
  Problem3Step6,
  Problem3Step7,
  Problem3Step8,
  Problem3Step9,
  Problem3Step10,
  Problem3Step11,
  Problem3Step12,
  Problem3Step16,
  Problem3Step17,
  Problem3Step18,
  Problem3Step19,
  Problem3Pedagogical1,
  Problem3Pedagogical2,
  Problem3Step20,
  Problem3Step21,
  Problem3Step22,
  Problem3Step23,
  Problem3Step24,
  Problem3Step25,
  Problem3Step26,
  Problem3Step27,
} from './Problem3Steps';
import { SectionMethodSolverL3 } from './SectionMethodSolverL3';
import { SimilarTrianglesSolverL3 } from './SimilarTrianglesSolverL3';
import { UDLDivisionSolverL3 } from './UDLDivisionSolverL3';

export const slides = {
  1: Problem3Divider,
  2: Problem3Step0,
  3: Problem3Step1,
  4: Problem3Step2,
  5: Problem3Step3,
  6: Problem3Step4,
  7: Problem3Step5,
  8: Problem3Step6,
  9: Problem3Step7,
  10: Problem3Step8,
  11: Problem3Step9,
  12: Problem3Step10,
  13: Problem3Step11,
  14: ZeroShearQuizL3,
  15: Problem3Step12,
  16: SectionMethodSolverL3,
  17: SimilarTrianglesSolverL3,
  18: UDLDivisionSolverL3,
  19: Problem3Step16,
  20: Problem3Step17,
  21: Problem3Step18,
  22: Problem3Step19,
  23: Problem3Pedagogical2,
  24: Problem3Pedagogical1,
  25: Problem3Step20,
  26: Problem3Step21,
  27: Problem3Step22,
  28: Problem3Step23,
  29: Problem3Step24,
  30: Problem3Step25,
  31: Problem3Step26,
  32: Problem3Step27,
};

export const sectionMetadata = {
  1: { title: 'Problem 3 Divider', type: 'Section Divider', section: 'Problem 3 Worked Example' },
  2: { title: 'Problem 3 Load Setup', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  3: { title: 'Problem 3 Reactions', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  4: { title: 'Problem 3 Discontinuities', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  5: { title: 'SFD Node A Jump', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  6: { title: 'SFD Segment A-C Integration', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  7: { title: 'SFD Node C Check', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  8: { title: 'SFD Segment C-D Integration', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  9: { title: 'SFD Node D Check', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  10: { title: 'SFD Segment D-E Integration', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  11: { title: 'SFD Node E Jump', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  12: { title: 'SFD Segment E-B Integration', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  13: { title: 'SFD Node B Jump', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  14: { title: 'Zero-Shear Crossing Checkpoint Quiz', type: 'Dynamic Quiz', section: 'Problem 3 Worked Example' },
  15: { title: 'Problem 3 Zero-Shear Point', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  16: { title: 'Solving Zero-Crossing - Section Method', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  17: { title: 'Solving Zero-Crossing - Similar Triangles', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  18: { title: 'Solving Zero-Crossing - UDL Division', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  19: { title: 'BMD Node A Check', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  20: { title: 'BMD Segment A-C Integration', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  21: { title: 'BMD Node C Check', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  22: { title: 'BMD Segment C-to-Peak Integration (Prediction)', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  23: { title: 'Applying Curvature to Segment C-to-Peak (Application)', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  24: { title: 'Slope-Moment Relationship Circle', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  25: { title: 'BMD Peak Moment Check', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  26: { title: 'BMD Segment Peak-to-D Integration', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  27: { title: 'BMD Node D Check', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  28: { title: 'BMD Segment D-E Integration', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  29: { title: 'BMD Node E Check', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  30: { title: 'BMD Segment E-B Integration', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  31: { title: 'BMD Node B Check', type: 'Concept Details', section: 'Problem 3 Worked Example' },
  32: { title: 'Problem 3 Solved Diagrams', type: 'Concept Details', section: 'Problem 3 Worked Example' },
};
